services:
  # Serviço web principal - API Flask
  - type: web
    name: orbe-nerd-api
    env: python
    buildCommand: pip install -r requirements.txt && backend/venv/Scripts/flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: IGDB_CLIENT_ID
        sync: false
      - key: IGDB_CLIENT_SECRET
        sync: false
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_PORT
        value: "5432"
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        value: postgres
      - key: SUPABASE_DB_PASSWORD
        sync: false
    healthCheckPath: /api/health

  # Serviço de sincronização de dados
  - type: worker
    name: orbe-nerd-data-sync
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python data_sync.py
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: IGDB_CLIENT_ID
        sync: false
      - key: IGDB_CLIENT_SECRET
        sync: false
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_PORT
        value: "5432"
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        value: postgres
      - key: SUPABASE_DB_PASSWORD
        sync: false