"""Initial migration to create tables

Revision ID: fcf80eeb0ff7
Revises: 
Create Date: 2025-09-18 08:22:54.264585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcf80eeb0ff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interacao')
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_curado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_url_api', sa.String(length=255), nullable=True))
        batch_op.alter_column('titulo_curado',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('data_lancamento_curada',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('data_lancamento_api',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('avaliacao',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('generos',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
        batch_op.alter_column('plataformas_curadas',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
        batch_op.alter_column('proximo_episodio',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
        batch_op.alter_column('staff',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('personagens',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_column('poster_url')

    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo_curado', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('titulo_api', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sinopse', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poster_curado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_url_api', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_lancamento_curada', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('data_lancamento_api', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('avaliacao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plataformas_curadas', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('em_cartaz', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('em_prevenda', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('duracao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('direcao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('roteiro', sa.String(length=255), nullable=True))
        batch_op.alter_column('generos',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
        batch_op.drop_column('titulo')
        batch_op.drop_column('popularidade')
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('poster_url')
        batch_op.drop_column('data_lancamento')
        batch_op.drop_column('backdrop_url')
        batch_op.drop_column('nota_media')
        batch_op.drop_column('descricao')

    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo_curado', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('titulo_api', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sinopse', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poster_curado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_url_api', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_lancamento_curada', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('data_lancamento_api', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('avaliacao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plataformas_curadas', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('desenvolvedores', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('publicadoras', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('lojas_digitais', sa.JSON(), nullable=True))
        batch_op.alter_column('generos',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
        batch_op.drop_column('titulo')
        batch_op.drop_column('popularidade')
        batch_op.drop_column('plataformas')
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('descricao')
        batch_op.drop_column('data_lancamento')
        batch_op.drop_column('nota_media')
        batch_op.drop_column('desenvolvedora')
        batch_op.drop_column('poster_url')

    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importante', sa.Boolean(), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('midia_id')
        batch_op.drop_column('tipo_midia')

    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo_curado', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('titulo_api', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sinopse', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poster_curado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_url_api', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_lancamento_curada', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('data_lancamento_api', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('avaliacao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plataformas_curadas', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('numero_temporadas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero_episodios', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('criadores', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.alter_column('generos',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
        batch_op.drop_column('titulo')
        batch_op.drop_column('popularidade')
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('poster_url')
        batch_op.drop_column('data_lancamento')
        batch_op.drop_column('backdrop_url')
        batch_op.drop_column('nota_media')
        batch_op.drop_column('descricao')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('preferencias',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('preferencias',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nota_media', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('backdrop_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_lancamento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('poster_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('popularidade', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('generos',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('criadores')
        batch_op.drop_column('numero_episodios')
        batch_op.drop_column('numero_temporadas')
        batch_op.drop_column('plataformas_curadas')
        batch_op.drop_column('avaliacao')
        batch_op.drop_column('data_lancamento_api')
        batch_op.drop_column('data_lancamento_curada')
        batch_op.drop_column('poster_url_api')
        batch_op.drop_column('poster_curado')
        batch_op.drop_column('sinopse')
        batch_op.drop_column('titulo_api')
        batch_op.drop_column('titulo_curado')

    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_midia', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('midia_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('importante')

    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('desenvolvedora', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nota_media', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_lancamento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plataformas', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('popularidade', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('generos',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('lojas_digitais')
        batch_op.drop_column('publicadoras')
        batch_op.drop_column('desenvolvedores')
        batch_op.drop_column('plataformas_curadas')
        batch_op.drop_column('avaliacao')
        batch_op.drop_column('data_lancamento_api')
        batch_op.drop_column('data_lancamento_curada')
        batch_op.drop_column('poster_url_api')
        batch_op.drop_column('poster_curado')
        batch_op.drop_column('sinopse')
        batch_op.drop_column('titulo_api')
        batch_op.drop_column('titulo_curado')

    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nota_media', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('backdrop_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_lancamento', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('poster_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('popularidade', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('generos',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('roteiro')
        batch_op.drop_column('direcao')
        batch_op.drop_column('duracao')
        batch_op.drop_column('em_prevenda')
        batch_op.drop_column('em_cartaz')
        batch_op.drop_column('plataformas_curadas')
        batch_op.drop_column('avaliacao')
        batch_op.drop_column('data_lancamento_api')
        batch_op.drop_column('data_lancamento_curada')
        batch_op.drop_column('poster_url_api')
        batch_op.drop_column('poster_curado')
        batch_op.drop_column('sinopse')
        batch_op.drop_column('titulo_api')
        batch_op.drop_column('titulo_curado')

    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('personagens',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('staff',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('proximo_episodio',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('plataformas_curadas',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('generos',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('avaliacao',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('data_lancamento_api',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('data_lancamento_curada',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('titulo_curado',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('poster_url_api')
        batch_op.drop_column('poster_curado')

    op.create_table('interacao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('midia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_midia', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tipo_interacao', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('valor', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_interacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('interacao_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interacao_pkey'))
    )
    # ### end Alembic commands ###
